version: "3.9"
services:
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./dist:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    volumes:
      - ./database/mysql/data:/var/lib/mysql

